[toolchain]
anchor_version = "0.32.1"

[features]
seeds = true

[programs.localnet]
escrow = "GCc4exWhx2tyw9ELQw8Y29izvXNG2FcVdfkYk8wo8BsF"

[programs.devnet]
escrow = "GCc4exWhx2tyw9ELQw8Y29izvXNG2FcVdfkYk8wo8BsF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[test.validator]
url = "https://api.mainnet-beta.solana.com"
bind_address = "127.0.0.1"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
